version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v2-<< parameters.ruby-version >>
      - run:
          name: Build shared libs
          command: bundle exec rake compile
      - run:
          name: Test
          command: bundle exec rspec
      - run:
          name: Simulate building the gem
          command: gem build *.gemspec

  publish_gem:
    docker:
      - image: jobseeker/docker-library:ruby-gem-publisher
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /source
    steps:
      - checkout
      - run:
          name: Setup GitHub token
          command: GITHUB_TOKEN=$GITHUB_PACKAGE_PUBLISH_ACCESS_TOKEN /opt/github_auth.sh
      - run:
          name: Build (and release) the gem
          command: rake -f /opt/Rakefile release

workflows:
  version: 2
  tests:
    jobs:
      - test:
          context: org-global
          matrix:
            parameters:
              ruby-version: ["2.7", "3.1", "3.2"]
      - publish_gem:
          context: org-global
          requires:
            - test
          filters:
            branches: { only: master }
